name: crud
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^3.4.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.2
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
